from dataclasses import asdict, dataclass
import json
from typing import Any, Literal
from pydantic import BaseModel, Field, field_validator


@dataclass(frozen=True)
class DocumentRecord:
    """Metadata kept for one successfully indexed PDF."""

    document_id: str
    original_filename: str
    stored_filename: str
    page_count: int
    pages_with_text: int
    chunk_count: int
    file_size_bytes: int
    created_at: str

    def to_public_dict(self) -> dict[str, str | int]:
        """Return only fields that are safe for API clients to see."""
        public_record = asdict(self)
        public_record.pop("stored_filename")
        return public_record


@dataclass(frozen=True)
class QuizAttemptRecord:
    """Persisted record of a student's quiz attempt."""

    attempt_id: str
    student_id: str
    document_id: str
    quiz_id: str
    quiz_title: str
    total_questions: int
    score: int
    time_spent_seconds: int
    submission_data_json: str
    created_at: str

    def to_dict(self) -> dict[str, Any]:
        """Return the record with parsed submission data."""
        data = asdict(self)
        try:
            data["submission_data"] = json.loads(self.submission_data_json)
        except Exception:
            data["submission_data"] = []
        return data


@dataclass(frozen=True)
class RecommendationRecord:
    """Persisted recommendation analysis generated by the Recommendation Agent."""

    recommendation_id: str
    attempt_id: str
    student_id: str
    document_id: str
    overall_score_percentage: float
    mastery_level: str
    summary: str
    topic_mastery_json: str
    knowledge_gaps_json: str
    action_items_json: str
    tutor_handoff_json: str
    created_at: str

    def to_dict(self) -> dict[str, Any]:
        """Return the recommendation record with parsed JSON structures."""
        record_dict = asdict(self)
        for json_key, target_key in [
            ("topic_mastery_json", "topic_mastery"),
            ("knowledge_gaps_json", "knowledge_gaps"),
            ("action_items_json", "action_items"),
            ("tutor_handoff_json", "tutor_handoff"),
        ]:
            try:
                record_dict[target_key] = json.loads(record_dict[json_key])
            except Exception:
                record_dict[target_key] = []
        return record_dict


# =====================================================================
# Pydantic Schemas for Inter-Agent Contracts and API Payloads
# =====================================================================


class QuestionMistakeDetail(BaseModel):
    """Detailed question response sent by Quiz Agent or Frontend."""

    question_id: str = Field(..., description="Unique question identifier")
    topic: str = Field(..., description="Topic or concept tag for the question")
    difficulty: Literal["easy", "medium", "hard"] = Field(
        default="medium", description="Difficulty level"
    )
    cognitive_level: Literal["recall", "understanding", "application", "analysis"] = (
        Field(default="understanding", description="Bloom's taxonomy cognitive level")
    )
    question_text: str = Field(..., description="Question statement")
    selected_answer: str = Field(..., description="Student's chosen answer")
    correct_answer: str = Field(..., description="Ground-truth correct answer")
    is_correct: bool = Field(..., description="Whether student answered correctly")
    explanation: str = Field(
        default="", description="Pedagogical explanation of the solution"
    )

    @field_validator("topic", "question_text", "selected_answer", "correct_answer")
    @classmethod
    def strip_and_validate(cls, value: str) -> str:
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("Field cannot be empty or whitespace only.")
        return cleaned


class QuizSubmissionRequest(BaseModel):
    """Validated input payload for quiz analysis submitted to Recommendation Agent."""

    student_id: str = Field(..., min_length=1, max_length=100, description="Student ID")
    document_id: str = Field(..., min_length=1, description="Associated document ID")
    quiz_id: str = Field(default="generic_quiz", description="Quiz ID")
    quiz_title: str = Field(
        default="Course Assessment", description="Title of the quiz"
    )
    time_spent_seconds: int = Field(
        default=0, ge=0, description="Total duration in seconds"
    )
    questions: list[QuestionMistakeDetail] = Field(
        ..., min_length=1, description="List of questions and answers"
    )

    @field_validator("student_id", "document_id", "quiz_id", "quiz_title")
    @classmethod
    def clean_strings(cls, value: str) -> str:
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("String field cannot be empty.")
        return cleaned


class TopicMastery(BaseModel):
    """Calculated mastery metrics for a single topic."""

    topic: str
    total_questions: int
    correct_count: int
    accuracy_percentage: float
    mastery_status: Literal["Mastered", "Review Needed", "Critical Gap"]
    weighted_severity_score: float
    difficulty_breakdown: dict[str, dict[str, int]]


class KnowledgeGap(BaseModel):
    """Identified concept gap with transparent explainability reasoning."""

    gap_id: str
    topic: str
    severity: Literal["CRITICAL", "MODERATE", "MINOR"]
    confidence_score: float = Field(
        ..., ge=0.0, le=1.0, description="Confidence in gap diagnosis"
    )
    explanation: str = Field(
        ..., description="Clear human-readable justification of the gap"
    )
    missed_questions_count: int
    sample_misconceptions: list[str]
    suggested_prerequisites: list[str] = Field(default_factory=list)


class StudyActionItem(BaseModel):
    """Prioritized actionable study step for the student."""

    priority: int = Field(..., ge=1, description="1 is highest priority")
    topic: str
    action_type: Literal["Review Lecture", "Practice Drills", "Deep Conceptual Review"]
    title: str
    description: str
    estimated_minutes: int
    lecture_citations: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Relevant document chunks and page numbers",
    )


class TutorHandoffPackage(BaseModel):
    """Ready-to-consume structured payload for the Tutor Agent."""

    recommendation_id: str
    student_id: str
    document_id: str
    target_topics: list[str]
    gap_severity: Literal["CRITICAL", "MODERATE", "MINOR", "NONE"]
    pedagogical_instruction: str
    suggested_opening_prompt: str
    relevant_lecture_chunks: list[dict[str, Any]] = Field(default_factory=list)


class RecommendationResponse(BaseModel):
    """Comprehensive explainable recommendation response."""

    recommendation_id: str
    attempt_id: str
    student_id: str
    document_id: str
    created_at: str
    overall_score: int
    total_questions: int
    score_percentage: float
    mastery_level: str
    summary: str
    topic_mastery: list[TopicMastery]
    knowledge_gaps: list[KnowledgeGap]
    action_items: list[StudyActionItem]
    tutor_handoff: TutorHandoffPackage


# =====================================================================
# Tutor Agent Dataclasses and Pydantic Schemas
# =====================================================================


@dataclass(frozen=True)
class TutorSessionRecord:
    """Metadata for one active or archived AI tutoring session."""

    session_id: str
    student_id: str
    document_id: str
    recommendation_id: str | None
    topic_focus: str
    mode: str
    created_at: str
    updated_at: str

    def to_dict(self) -> dict[str, Any]:
        """Convert dataclass to dictionary."""
        return asdict(self)


@dataclass(frozen=True)
class TutorMessageRecord:
    """Individual conversational turn in a tutoring session."""

    message_id: str
    session_id: str
    role: str  # 'student', 'tutor', or 'system'
    content: str
    citations_json: str
    created_at: str

    def to_dict(self) -> dict[str, Any]:
        """Convert dataclass to dictionary with parsed citations."""
        data = asdict(self)
        try:
            data["citations"] = json.loads(self.citations_json)
        except Exception:
            data["citations"] = []
        return data


class TutorSessionInitRequest(BaseModel):
    """Payload to start a new Socratic or Step-by-Step tutoring session."""

    student_id: str = Field(..., min_length=1, max_length=100, description="Student ID")
    document_id: str = Field(..., min_length=1, description="Associated document ID")
    recommendation_id: str | None = Field(
        default=None, description="Optional recommendation ID to auto-load handoff"
    )
    mode: Literal["socratic", "step_by_step", "concept_check"] = Field(
        default="socratic", description="Teaching pedagogical mode"
    )
    topic_focus: str | None = Field(
        default=None, description="Optional primary topic or concept to focus on"
    )

    @field_validator("student_id", "document_id")
    @classmethod
    def clean_strings(cls, value: str) -> str:
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("Identifier field cannot be empty.")
        return cleaned


class TutorChatRequest(BaseModel):
    """Payload sent by student during an active chat turn."""

    session_id: str = Field(..., min_length=1, description="Active session ID")
    message: str = Field(..., min_length=1, max_length=4000, description="Student's query or answer")
    mode: Literal["socratic", "step_by_step", "concept_check"] | None = Field(
        default=None, description="Optional override for pedagogical mode"
    )

    @field_validator("session_id", "message")
    @classmethod
    def clean_text(cls, value: str) -> str:
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("Field cannot be empty.")
        return cleaned


class TutorChatResponse(BaseModel):
    """Structured response from the Tutor Agent."""

    session_id: str
    message_id: str
    reply: str
    mode: str
    citations: list[dict[str, Any]] = Field(
        default_factory=list, description="Grounding lecture citations and page numbers"
    )
    suggested_followups: list[str] = Field(
        default_factory=list, description="Interactive quick-reply prompt options for student"
    )
    concept_check_question: str | None = Field(
        default=None, description="Optional comprehension check question"
    )
    created_at: str


class TutorSessionResponse(BaseModel):
    """Full session details with chat history."""

    session_id: str
    student_id: str
    document_id: str
    recommendation_id: str | None
    topic_focus: str
    mode: str
    messages: list[dict[str, Any]]
    created_at: str
    updated_at: str

